version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres-vector
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: InfoMaisSaude-RagArchitecture
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:alpine
    container_name: evolution-redis
    restart: always
    command: redis-server --appendonly yes --requirepass minha_senha_redis
    volumes:
      - ./redis_data:/data

  evolution:
    image: atendai/evolution-api:v2.1.1
    container_name: evolution-api
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./evolution_store:/evolution/store
    environment:
      SERVER_URL: http://localhost:8081
      AUTHENTICATION_API_KEY: ${EVOLUTION_API_KEY}
      
      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: "postgresql"
      DATABASE_CONNECTION_URI: "postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/InfoMaisSaude-RagArchitecture?schema=evolution"
      
      CACHE_REDIS_ENABLED: "true"
      CACHE_REDIS_URI: "redis://:minha_senha_redis@redis:6379/0"
      
      LOG_LEVEL: error 
      DEL_INSTANCE: "false"
    depends_on:
      - db
      - redis

  app:
    build: .
    container_name: infomaissaude-backend-rag
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/InfoMaisSaude-RagArchitecture
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      
      EVOLUTION_API_URL: http://evolution:8080
      EVOLUTION_API_KEY: ${EVOLUTION_API_KEY}
      EVOLUTION_INSTANCE_NAME: infomaissaudebot
      
    depends_on:
      - db
      - evolution

  caddy:
    image: caddy:latest
    container_name: caddy-https
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - app

volumes:
  caddy_data: