version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres-vector
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: InfoMaisSaude-RagArchitecture
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: infomaissaude-backend-rag
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/InfoMaisSaude-RagArchitecture
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      
      META_API_TOKEN: ${META_API_TOKEN}
      META_PHONE_ID: ${META_PHONE_ID}
      META_WEBHOOK_VERIFY_TOKEN: ${META_WEBHOOK_VERIFY_TOKEN}
    depends_on:
      - db

  caddy:
    image: caddy:latest
    container_name: caddy-https
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - app

volumes:
  caddy_data: