version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: postgres-vector
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: InfoMaisSaude-RagArchitecture
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  wppconnect:
    image: wppconnect/wppconnect-server:latest
    container_name: wppconnect
    restart: always
    ports:
      - "21465:21465" 
    volumes:
      - ./wpp_sessions:/usr/src/app/tokens 
    environment:
      SERVER_PORT: 21465
      SERVER_SECRET_KEY: minha_senha_secreta_wpp
      WEBHOOK_URL: http://infomaissaude-backend-rag:8080/webhook
      LOG_LEVEL: error
      BROWSER_ARGS: "--no-sandbox --disable-setuid-sandbox"

  app:
    build: .
    container_name: infomaissaude-backend-rag
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/InfoMaisSaude-RagArchitecture
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      
      WPP_URL: http://wppconnect:21465
      WPP_SECRET: minha_senha_secreta_wpp
      WPP_SESSION: sessao_medica 
      
    depends_on:
      - db
      - wppconnect

  caddy:
    image: caddy:latest
    container_name: caddy-https
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - app

volumes:
  caddy_data: